default:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-destination
      user: dbtuser
      pass: pssd
      port: 5432
      dbname: dbtdb
      schema: dbt
      threads: 4